import test from 'node:test';
import assert from 'node:assert/strict';
import {syncRequest,googlePath} from './google-data-client.mjs';
test('Gmail metadata payload',()=>assert.deepEqual(syncRequest('mail','ops.assistant','gmail'),{agent:'ops.assistant',kind:'gmail',calendar:''}));
test('Calendar ID stays data',()=>assert.equal(syncRequest('mail','ops','calendar','team@example.invalid').calendar,'team@example.invalid'));
test('Calendar needs ID',()=>assert.throws(()=>syncRequest('mail','ops','calendar')));
test('Non calendar rejects ID',()=>assert.throws(()=>syncRequest('mail','ops','drive','primary')));
test('Reject unknown provider',()=>assert.throws(()=>syncRequest('mail','ops','custom')));
test('Reject connection URL',()=>assert.throws(()=>syncRequest('https://evil.invalid','ops','gmail')));
test('Reject agent path traversal',()=>assert.throws(()=>syncRequest('mail','../ops','gmail')));
test('Reject calendar control chars',()=>assert.throws(()=>syncRequest('mail','ops','calendar','x\nY')));
test('Reject oversized calendar',()=>assert.throws(()=>syncRequest('mail','ops','calendar','x'.repeat(257))));
test('Pinned app route',()=>assert.equal(googlePath('tenant','google','page'),'/platform/tenant/google/google/sync/page'));
test('Reject caller endpoint',()=>assert.throws(()=>googlePath('tenant','google','../../send')));
test('Reject bad tenant',()=>assert.throws(()=>googlePath('../t','google','page')));
test('Reject non-string identities',()=>{for(const value of [undefined,null,22,{},['mail']])assert.throws(()=>syncRequest(value,'ops','gmail'));});
test('Reject trailing newline identity',()=>assert.throws(()=>syncRequest('mail\n','ops','gmail')));
test('Reject non-string tenant',()=>assert.throws(()=>googlePath(undefined,'google','page')));
test('Reject missing agent',()=>assert.throws(()=>syncRequest('mail',undefined,'gmail')));
