export type ShopResource='approvals'|'inbox'|'products'|'orders'|'channels';
export function shopPath(tenant:string,resource:ShopResource):string;
export function approvalPath(tenant:string,step:string):string;
export function canReadInbox(role:string):boolean;
import type {OrderView} from './conversation-client.mjs';
export type Draft={kind:'message';channel:string;recipient:string;text:string}|{kind:'order';title:string;order:OrderView}|{kind:'args';text:string};
export function draftSummary(tool:string,args:unknown):Draft;
export function wholeNumber(value:string,min?:number,max?:number):number;
export function formatSum(value:number,currency?:string):string;
export function formatMinor(minor:number,currency?:string):string;
export function safePhotoUrl(value:unknown):string;
export type StockView={tracked:boolean;total:number|null;sizes:{size:string;qty:number|null}[]};
export function stockView(product:{sizes?:unknown[];stock?:Record<string,number>}|null|undefined):StockView;
export function bootstrapBody(fields:{email:string;password:string;displayName:string;workspaceId:string;workspaceName:string}):{email:string;password:string;display_name:string;workspace_id:string;workspace_name:string};
export function startAutoRefresh(fn:()=>unknown,interval?:number,env?:{setInterval:typeof setInterval;clearInterval:typeof clearInterval;document?:{hidden:boolean;addEventListener?:(name:string,fn:()=>unknown)=>void;removeEventListener?:(name:string,fn:()=>unknown)=>void}}):()=>void;
